config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "quotations#index"

  get 'spareparts/index' => 'spareparts#index', as: 'spareparts'
  get 'spareparts/:id/add' => 'spareparts#add', as: 'add_sparepart'
  get 'labours/index' => 'labours#index', as: 'labours'
  get 'labours/:id/add' => 'labours#add', as: 'add_labour'
  get 'quotations/index' => 'quotations#index', as: 'quotations'
  post 'quotations/add_discount' => 'quotations#add_discount', as: 'quotation_add_discount'
  get 'quotations/order_details' => 'quotations#order_details', as: 'quotation_details'
  get 'quotations/order_saved' => 'quotations#order_saved', as: 'quotation_saved'
  get 'quotations/order_reset' => 'quotations#order_rest', as: 'quotation_reset'
  get 'quotations/:id/views' => 'quotations#views', as: 'quotation_views'
  get 'quotations/:id/get_html' => 'quotations#get_html', as: 'quotation_get_html'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/labour.rb
class Labour < ApplicationRecord
	has_many :quotation_labours
end

app/models/quotation.rb
class Quotation < ApplicationRecord
	has_many :quotation_labours
	has_many :quotation_spareparts

	def list_spareparts
		spareparts = ""
		s = Sparepart.where(id: self.quotation_spareparts.pluck(:sparepart_id))
		s.each do |x|
			spareparts << "- #{x.name} <br/>"
		end
		return spareparts.html_safe
	end

	def list_labours
		labours = ""
		s = Labour.where(id: self.quotation_labours.pluck(:labour_id))
		s.each do |x|
			labours << "- #{x.name} <br/>"
		end
		return labours.html_safe
	end
end

app/models/quotation_labour.rb
class QuotationLabour < ApplicationRecord
end

app/models/quotation_sparepart.rb
class QuotationSparepart < ApplicationRecord
end

app/models/sparepart.rb
class Sparepart < ApplicationRecord
	has_many :quotation_spareparts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :quotation_adds

	def quotation_adds
session['spareparts'] = [] unless session['spareparts']
session['labours'] = [] unless session['labours']
session['discount'] = [] unless session['discount']

#session['spareparts'] = []
#session['labours'] = []
#session['discount'] = nil

		@add_spareparts = session['spareparts']
		@add_labours = session['labours']
		@add_discount = session['discount']
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index

	end
end

app/controllers/labours_controller.rb
class LaboursController < ApplicationController
	def index
		if params[:find]
			@labours = Labour.where("name LIKE ?", "%#{params[:find]}%")
		else
			@labours = Labour.all
		end
	end

	def add
		return (flash[:error] = "cannot add labour to quotations" and redirect_to labours_path) unless params[:id]
		return (@add_labours.delete(params[:id].to_s) and flash[:notice] = "removed labour from quotations" and redirect_back(fallback_location: root_path)) if params[:remove]
		@add_labours << params[:id]
		flash[:notice] = "successfully add labour to quotations"
		redirect_to labours_path
	end
end

app/controllers/quotations_controller.rb
class QuotationsController < ApplicationController
	def index
		@quotations = Quotation.all
	end

	def order_details
		return (flash[:error] = "please add spareparts and labours first" and redirect_to spareparts_path) if @add_spareparts.blank? || @add_labours.blank?
		@spareparts = Sparepart.where(id: @add_spareparts) rescue []
		@labours = Labour.where(id: @add_labours) rescue []

		@total_order = (@spareparts.pluck(:price).sum + @labours.pluck(:price).sum ) rescue 0
		@total_order = (@total_order - (@total_order * @add_discount / 100)) rescue 0
	end

	def add_discount
		return (flash[:error] = "please input discount.." and redirect_back(fallback_location: root_path)) if params[:discount].blank?

		return (flash[:error] = "discount not found" and redirect_back(fallback_location: root_path)) if params[:discount].present? && params[:discount] != 'MRDISCOUNT'
		session['discount'] = 10
		flash[:notice] = "successfully add discount"
		redirect_back(fallback_location: root_path)
	end

	def order_saved
		@spareparts = Sparepart.where(id: @add_spareparts) rescue []
		@labours = Labour.where(id: @add_labours) rescue []

		total_order = (@spareparts.pluck(:price).sum + @labours.pluck(:price).sum ) rescue 0
		total_order = total_order - ((total_order * @add_discount / 100) rescue 0)

		quotation = Quotation.new
		quotation.total_price = total_order
		quotation.discount = @add_discount
		quotation.save
		@add_spareparts.each do |qs|
			QuotationSparepart.create(quotation_id: quotation.id, sparepart_id: qs)
			puts qs
		end

		@add_labours.each do |qs|
			QuotationLabour.create(quotation_id: quotation.id, labour_id: qs)
			puts qs
		end

		flash[:notice] = "successfully Saved Quotation"
		session['spareparts'] = []
		session['labours'] = []
		session['discount'] = nil
		redirect_to root_path
	end

	def order_reset
		session['spareparts'] = []
		session['labours'] = []
		session['discount'] = nil

		flash[:notice] = "successfully Reset Quotations"
		redirect_to root_path

	end

	def views
		@quotation = Quotation.find_by_id(params[:id])
		return (flash[:error] = "quotation not found" and redirect_back(fallback_location: root_path)) if params[:id].blank?
		qs = @quotation.quotation_spareparts.pluck(:sparepart_id) rescue []
		ql = @quotation.quotation_labours.pluck(:labour_id) rescue []
		@spareparts = Sparepart.where(id: qs) rescue []
		@labours = Labour.where(id: ql) rescue []
		respond_to do |format|
	      format.html
	      format.pdf do |pdf|
			@pdf = WickedPdf.new.pdf_from_url("#{root_url}/quotations/#{@quotation.id}/get_html")
			send_data(@pdf, filename: "#{@quotation.id}_quotaion_reviewed.pdf", type: "application/pdf")
		  end
	    end
	end

	def get_html
		@quotation = Quotation.find_by_id(params[:id])
		return (flash[:error] = "quotation not found" and redirect_back(fallback_location: root_path)) if params[:id].blank?
		qs = @quotation.quotation_spareparts.pluck(:sparepart_id) rescue []
		ql = @quotation.quotation_labours.pluck(:labour_id) rescue []
		@spareparts = Sparepart.where(id: qs) rescue []
		@labours = Labour.where(id: ql) rescue []
		render layout: 'get_html'
	end
end

app/controllers/spareparts_controller.rb
class SparepartsController < ApplicationController
	def index
		if params[:find]
			@spareparts = Sparepart.where("name LIKE ?", "%#{params[:find]}%")
		else
			@spareparts = Sparepart.all
		end
	end

	def add
		return (flash[:error] = "cannot add sparepart to quotations" and redirect_to spareparts_path) unless params[:id]
		return (@add_spareparts.delete(params[:id].to_s) and flash[:notice] = "removed sparepart from quotations" and redirect_back(fallback_location: root_path)) if params[:remove]
		@add_spareparts << params[:id]
		flash[:notice] = "successfully add sparepart to quotations"
		redirect_to spareparts_path
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/labours_helper.rb
module LaboursHelper
end

app/helpers/quotations_helper.rb
module QuotationsHelper
end

app/helpers/spareparts_helper.rb
module SparepartsHelper
end

app/views/home/index.html.erb
test

app/views/labours/index.html.erb
<div class="m-grid__item m-grid__item--fluid m-wrapper">

  <!-- BEGIN: Subheader -->
  <div class="m-subheader ">
    <div class="d-flex align-items-center">
      <div class="mr-auto">
        <h3 class="m-subheader__title ">Labours</h3>
      </div>
    </div>
  </div>

  <!-- END: Subheader -->
  <div class="m-content">

    <!--Begin::Section-->
    <div class="row">
      <div class="col-xl-12">

        <!--begin:: Widgets/Top Products-->
        <div class="m-portlet m-portlet--mobile m-portlet--full-height ">
          <div class="m-portlet__head">
            <div class="m-portlet__head-caption">
              <div class="m-portlet__head-title">
                <h3 class="m-portlet__head-text">
                  Labours List
                </h3>
              </div>
            </div>
            <div class="m-portlet__head-tools">
              <div class="m-form__group">
                <a href="<%= spareparts_path  %>" class="btn btn-success">
                  <i class="la la-angle-left"></i>
                  <span>View Back to Add Spare Part</span>
                </a>
                <a href="<%= quotation_details_path  %>" class="btn btn-primary">
                  <i class="la la-angle-right"></i><i class="la la-angle-right"></i>
                  <span>View Detail</span>
                </a>
              </div>
            </div>
          </div>
          <div class="m-portlet__body">
            <div class="m-section">
              <div class="m-section__content">
                <div id="m_table_1_wrapper" class="dataTables_wrapper dt-bootstrap4 no-footer">
                  <div class="row" style="margin-bottom: 20px">
                    <div class="col-sm-12 col-md-6">
                    </div>
                    <div class="col-sm-12 col-md-6">
                      <div id="m_table_1_filter" class="dataTables_filter">
                        <label>Search:
                          <input type="search" class="form-control search_name" placeholder="search sparepart.. " aria-controls="m_table_1" style="min-width: 250px;" name="find" value="<%= params[:find] %>">
                        </label>
                      </div>
                    </div>
                  </div>
                  <div class="table-responsive">
                    <table class="table table-striped- table-bordered table-hover table-checkable" id="m_table_1">
                      <thead>
                        <tr class="text-center">
                          <th>Date</th>
                          <th>Name</th>
                          <th>Desc</th>
                          <th>Price</th>
                          <th></th>
                        </tr>
                      </thead>
                      <tbody>

                        <% @labours.each do |p|%>
                        <tr class='clickable-row' data-href='#'>
                           <td><%= p.created_at.to_date %></td>
				          	<td><%= p.name rescue '-' %></td>
                    <td><%= p.desc rescue '-' %></td>
				          	<td>$<%= p.price rescue '-' %></td>
                          <td>
                            <% if (@add_labours.include?(p.id.to_s) rescue false) %>
                              <a href="<%= add_labour_path(p.id, remove: true) %>" class="btn btn-default m-btn m-btn--icon" title="Edit" style="margin-bottom: 5px;">
                                <span>
                                  <i class="la la-remove"></i>
                                  <span>Remove</span>
                                </span>
                              </a>
                            <% else %>
                              <a href="<%= add_labour_path(p.id) %>" class="btn btn-success m-btn m-btn--icon" title="Edit" style="margin-bottom: 5px;">
                                  <span>
                                    <i class="la la-plus"></i>
                                    <span>Add</span>
                                  </span>
                                </a>
                            <% end %>
                          </td>
                        </tr>
                        <% end %>
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!--end:: Widgets/Top Products-->
      </div>
    </div>

    <!--End::Section-->

  </div>
</div>

app/views/quotations/index.html.erb
<div class="m-grid__item m-grid__item--fluid m-wrapper">

  <!-- BEGIN: Subheader -->
  <div class="m-subheader ">
    <div class="d-flex align-items-center">
      <div class="mr-auto">
        <h3 class="m-subheader__title ">Quotations</h3>
      </div>
    </div>
  </div>

  <!-- END: Subheader -->
  <div class="m-content">

    <!--Begin::Section-->
    <div class="row">
      <div class="col-xl-12">

        <!--begin:: Widgets/Top Products-->
        <div class="m-portlet m-portlet--mobile m-portlet--full-height ">
          <div class="m-portlet__head">
            <div class="m-portlet__head-caption">
              <div class="m-portlet__head-title">
                <h3 class="m-portlet__head-text">
                  Quotations List
                </h3>
              </div>
            </div>
            <div class="m-portlet__head-tools">
              <div class="m-form__group">
                <a href="<%= spareparts_path  %>" class="btn btn-primary">
                  <i class="flaticon-add-circular-button"></i>
                  <span>Order Sparepart</span>
                </a>
              </div>
            </div>
          </div>
          <div class="m-portlet__body">
            <div class="m-section">
              <div class="m-section__content">
                <div id="m_table_1_wrapper" class="dataTables_wrapper dt-bootstrap4 no-footer">
                  <div class="row" style="margin-bottom: 20px">
                    <div class="col-sm-12 col-md-6">
                    </div>
                  </div>
                  <div class="table-responsive">
                    <table class="table table-striped- table-bordered table-hover table-checkable" id="m_table_1">
                      <thead>
                        <tr class="text-center">
                          <th>Date</th>
                          <th>Spareparts</th>
                          <th>Labours </th>
                          <th>Discount (%)</th>
                          <th>Total Order</th>
                        </tr>
                      </thead>
                      <tbody>

                        <% @quotations.each do |p|%>
                        <tr class='clickable-row' data-href='#'>
                           <td><%= p.created_at.strftime("%a, %m-%Y %H:%M") %></td>
				          	<td><%= p.list_spareparts %></td>
				          	<td><%= p.list_labours %></td>
				          	<td><%= p.discount %></td>
				          	<td>$<%= p.total_price rescue '-'%></td>
                          <td>
                            <a href="<%= quotation_views_path(p.id) %>" class="btn btn-success m-btn m-btn--icon" title="Edit" style="margin-bottom: 5px;">
                              <span>
                                <i class="la la-edit"></i>
                                <span>Detail</span>
                              </span>
                            </a>
                          </td>
                        </tr>
                        <% end %>
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!--end:: Widgets/Top Products-->
      </div>
    </div>

    <!--End::Section-->

  </div>
</div>

app/views/quotations/order_details.html.erb
<div class="m-grid__item m-grid__item--fluid m-wrapper">

  <!-- BEGIN: Subheader -->
  <div class="m-subheader ">
    <div class="d-flex align-items-center">
      <div class="mr-auto">
        <h3 class="m-subheader__title ">Quotation Review</h3>
      </div>
    </div>
  </div>

  <!-- END: Subheader -->
  <div class="m-content">

    <!--Begin::Section-->
    <div class="row">
      <div class="col-xl-6">

        <!--begin:: Widgets/Top Products-->
        <div class="m-portlet m-portlet--mobile m-portlet--full-height ">
          <div class="m-portlet__head">
            <div class="m-portlet__head-caption">
              <div class="m-portlet__head-title">
                <h3 class="m-portlet__head-text">
                  Spare Part Review
                </h3>
              </div>
            </div>
            <div class="m-portlet__head-tools">
              <div class="m-form__group">
                <a href="<%= spareparts_path  %>" class="btn btn-primary">
                  <i class="flaticon-add-circular-button"></i>
                  <span>Add More Spare Parts</span>
                </a>
              </div>
            </div>
          </div>
          <div class="m-portlet__body">
            <div class="m-section">
              <div class="m-section__content">
                <div id="m_table_1_wrapper" class="dataTables_wrapper dt-bootstrap4 no-footer">
                  <div class="table-responsive">
                    <table class="table table-striped- table-bordered table-hover table-checkable" id="m_table_1">
                      <thead>
                        <tr class="text-center">
                          <th>Name</th>
                          <th>Price</th>
                          <th></th>
                        </tr>
                      </thead>
                      <tbody>

                        <% @spareparts.each do |p|%>
                        <tr class='clickable-row' data-href='#'>
                    <td><%= p.name rescue '-' %></td>
                    <td>$<%= p.price rescue '-' %></td>
                          <td>
                            <% if @add_spareparts.include?(p.id.to_s) %>
                              <a href="<%= add_sparepart_path(p.id, remove: true) %>" class="btn btn-default m-btn m-btn--icon" title="Edit" style="margin-bottom: 5px;">
                                <span>
                                  <i class="la la-remove"></i>
                                  <span>Remove</span>
                                </span>
                              </a>
                            <% else %>
                              <a href="<%= add_sparepart_path(p.id) %>" class="btn btn-success m-btn m-btn--icon" title="Edit" style="margin-bottom: 5px;">
                                  <span>
                                    <i class="la la-plus"></i>
                                    <span>Add</span>
                                  </span>
                                </a>
                            <% end %>
                          </td>
                        </tr>
                        <% end %>
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
          </div>

        </div>
        <!--end:: Widgets/Top Products-->
      </div>

      <div class="col-xl-6">

        <!--begin:: Widgets/Top Products-->
        <div class="m-portlet m-portlet--mobile m-portlet--full-height ">
          <div class="m-portlet__head">
            <div class="m-portlet__head-caption">
              <div class="m-portlet__head-title">
                <h3 class="m-portlet__head-text">
                  Labours Review
                </h3>
              </div>
            </div>
            <div class="m-portlet__head-tools">
              <div class="m-form__group">
                <a href="<%= labours_path  %>" class="btn btn-primary">
                  <i class="flaticon-add-circular-button"></i>
                  <span>Add More Labours</span>
                </a>
              </div>
            </div>
          </div>
          <div class="m-portlet__body">
            <div class="m-section">
              <div class="m-section__content">
                <div id="m_table_1_wrapper" class="dataTables_wrapper dt-bootstrap4 no-footer">
                  <div class="table-responsive">
                    <table class="table table-striped- table-bordered table-hover table-checkable" id="m_table_1">
                      <thead>
                        <tr class="text-center">
                          <th>Name</th>
                          <th>Price</th>
                          <th></th>
                        </tr>
                      </thead>
                      <tbody>

                        <% @labours.each do |p|%>
                        <tr class='clickable-row' data-href='#'>
                    <td><%= p.name rescue '-' %></td>
                    <td>$<%= p.price rescue '-' %></td>
                          <td>
                            <% if @add_labours.include?(p.id.to_s) %>
                              <a href="<%= add_labour_path(p.id, remove: true) %>" class="btn btn-default m-btn m-btn--icon" title="Edit" style="margin-bottom: 5px;">
                                <span>
                                  <i class="la la-remove"></i>
                                  <span>Remove</span>
                                </span>
                              </a>
                            <% else %>
                              <a href="<%= add_labour_path(p.id) %>" class="btn btn-success m-btn m-btn--icon" title="Edit" style="margin-bottom: 5px;">
                                  <span>
                                    <i class="la la-plus"></i>
                                    <span>Add</span>
                                  </span>
                                </a>
                            <% end %>
                          </td>
                        </tr>
                        <% end %>
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!--end:: Widgets/Top Products-->
      </div>

      <div class="col-xl-6">
          <div class="m-portlet m-portlet--tabs m-portlet--full-height product-portlet">
            <div class="m-portlet__head">
              <div class="m-portlet__head-caption">
                <div class="m-portlet__head-title">
                  <h5>
                    Add Discount
                  </h5>
                </div>
              </div>
            </div>
            <div class="m-portlet__body">
              <div class="row" style="margin-bottom:30px;">
                <%= form_tag quotation_add_discount_path do  %>
                <div class="form-group m-form__group">
                  <%= text_field_tag 'discount', nil, class: "form-control m-input m-input--solid", placeholder: 'input discount here..' %>
                </div>
                <div class="form-group m-form__group">
                  * input "MRDISCOUNT" to get 10% discount <br/><br/>
                  <%= submit_tag 'process', class: 'btn btn-success' %>
                </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>

      <div class="col-xl-6">
          <div class="m-portlet m-portlet--tabs m-portlet--full-height product-portlet">
            <div class="m-portlet__head">
              <div class="m-portlet__head-caption">
                <div class="m-portlet__head-title">
                  <h5>
                    Detail Order
                  </h5>
                </div>
              </div>
            </div>
            <div class="m-portlet__body">
              <div class="row" style="margin-bottom:30px;">
                <div class="col-xl-8">
                  <div class="order-info">
                    <div class="fblock clearfix">
                      <div class="label">Order Date</div>
                      <div class="text"><%= Time.now.strftime("%a, %m-%Y %H:%M") %></div>
                    </div>
                    <div class="fblock clearfix">
                      <div class="label">Spareparts Order</div>
                      <div class="text">$<%= @spareparts.pluck(:price).sum %></div>
                    </div>
                    <div class="fblock clearfix">
                      <div class="label">Labours Order</div>
                      <div class="text">$<%= @labours.pluck(:price).sum %></div>
                    </div>
                    <div class="fblock clearfix">
                      <div class="label">Discount (%)</div>
                      <div class="text"><%= @add_discount.to_i rescue 0 %></div>
                    </div>
                    <div class="fblock clearfix">
                      <div class="label">Total Order</div>
                      <div class="text">$<%= @total_order %></div>
                    </div>

                  </div>
                </div>

              </div>
            </div>
          </div>
      </div>
      <div class="col-xl-12">
          <a href="<%= quotation_saved_path %>" class="btn btn-success" style="display: inline-block;">
            <i class="la la-save"></i>
            <span>Save Quotation</span>
          </a>
          <a href="<%= quotation_reset_path %>" class="btn btn-danger" style="display: inline-block;">
            <i class="flaticon-delete"></i>
            <span>Reset Quotation</span>
          </a>
        </div>
    </div>

    <!--End::Section-->

  </div>
</div>

app/views/quotations/views.html.erb
<div class="m-grid__item m-grid__item--fluid m-wrapper">

  <!-- BEGIN: Subheader -->
  <div class="m-subheader ">
    <div class="d-flex align-items-center">
      <div class="mr-auto">
        <h3 class="m-subheader__title ">Quotation Detail</h3>
      </div>
      <div>
        <a href="<%= quotation_views_path(@quotation.id, format: :pdf ) %>" class="btn btn-success" style="display: inline-block;">
          <i class="la la-save"></i>
          <span>Export to PDF</span>
        </a>
      </div>
    </div>
  </div>

  <!-- END: Subheader -->
  <div class="m-content">

    <!--Begin::Section-->
    <div class="row">
      <div class="col-xl-6">

        <!--begin:: Widgets/Top Products-->
        <div class="m-portlet m-portlet--mobile m-portlet--full-height ">
          <div class="m-portlet__head">
            <div class="m-portlet__head-caption">
              <div class="m-portlet__head-title">
                <h3 class="m-portlet__head-text">
                  Spare Part Detail
                </h3>
              </div>
            </div>
          </div>
          <div class="m-portlet__body">
            <div class="m-section">
              <div class="m-section__content">
                <div id="m_table_1_wrapper" class="dataTables_wrapper dt-bootstrap4 no-footer">
                  <div class="table-responsive">
                    <table class="table table-striped- table-bordered table-hover table-checkable" id="m_table_1">
                      <thead>
                        <tr class="text-center">
                          <th>Name</th>
                          <th>Price</th>
                          <th></th>
                        </tr>
                      </thead>
                      <tbody>

                        <% @spareparts.each do |p|%>
                        <tr class='clickable-row' data-href='#'>
                    <td><%= p.name rescue '-' %></td>
                    <td>$<%= p.price rescue '-' %></td>
                        </tr>
                        <% end %>
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
          </div>

        </div>
        <!--end:: Widgets/Top Products-->
      </div>

      <div class="col-xl-6">

        <!--begin:: Widgets/Top Products-->
        <div class="m-portlet m-portlet--mobile m-portlet--full-height ">
          <div class="m-portlet__head">
            <div class="m-portlet__head-caption">
              <div class="m-portlet__head-title">
                <h3 class="m-portlet__head-text">
                  Labours Detail
                </h3>
              </div>
            </div>
          </div>
          <div class="m-portlet__body">
            <div class="m-section">
              <div class="m-section__content">
                <div id="m_table_1_wrapper" class="dataTables_wrapper dt-bootstrap4 no-footer">
                  <div class="table-responsive">
                    <table class="table table-striped- table-bordered table-hover table-checkable" id="m_table_1">
                      <thead>
                        <tr class="text-center">
                          <th>Name</th>
                          <th>Price</th>
                          <th></th>
                        </tr>
                      </thead>
                      <tbody>

                        <% @labours.each do |p|%>
                        <tr class='clickable-row' data-href='#'>
                    <td><%= p.name rescue '-' %></td>
                    <td>$<%= p.price rescue '-' %></td>
                        </tr>
                        <% end %>
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!--end:: Widgets/Top Products-->
      </div>

      <div class="col-xl-12">
          <div class="m-portlet m-portlet--tabs m-portlet--full-height product-portlet">
            <div class="m-portlet__head">
              <div class="m-portlet__head-caption">
                <div class="m-portlet__head-title">
                  <h5>
                    Detail Order
                  </h5>
                </div>
              </div>
            </div>
            <div class="m-portlet__body">
              <div class="row" style="margin-bottom:30px;">
                <div class="col-xl-4">
                  <div class="order-info">
                    <div class="fblock clearfix">
                      <div class="label">Order Date</div>
                      <div class="text"><%= @quotation.created_at.strftime("%a, %m-%Y %H:%M") %></div>
                    </div>
                    <div class="fblock clearfix">
                      <div class="label">Spareparts Order</div>
                      <div class="text">$<%= @spareparts.pluck(:price).sum %></div>
                    </div>
                    <div class="fblock clearfix">
                      <div class="label">Labours Order</div>
                      <div class="text">$<%= @labours.pluck(:price).sum %></div>
                    </div>
                    <div class="fblock clearfix">
                      <div class="label">Discount (%)</div>
                      <div class="text"><%= @quotation.discount.to_i rescue 0 %></div>
                    </div>
                    <div class="fblock clearfix">
                      <div class="label">Total Order</div>
                      <div class="text">$<%= @quotation.total_price %></div>
                    </div>

                  </div>
                </div>

              </div>
            </div>
          </div>
      </div>
    </div>

    <!--End::Section-->

  </div>
</div>